// <auto-generated />
using System;
using FirstWebMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstWebMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260414105559_CacBangThuongMaiDienTu")]
    partial class CacBangThuongMaiDienTu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("FirstWebMVC.Models.Entities.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = "KH01",
                            FullName = "Học Viên VIP",
                            Phone = "0999999999"
                        });
                });

            modelBuilder.Entity("FirstWebMVC.Models.Entities.Faculty", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoas");

                    b.HasData(
                        new
                        {
                            MaKhoa = "CNTT",
                            TenKhoa = "Công nghệ thông tin"
                        },
                        new
                        {
                            MaKhoa = "KETOAN",
                            TenKhoa = "Kế toán"
                        },
                        new
                        {
                            MaKhoa = "QTKD",
                            TenKhoa = "Quản trị kinh doanh"
                        },
                        new
                        {
                            MaKhoa = "CD",
                            TenKhoa = "Cơ điện"
                        });
                });

            modelBuilder.Entity("FirstWebMVC.Models.Entities.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = "DH_MOHANG",
                            CustomerId = "KH01",
                            OrderDate = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FirstWebMVC.Models.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = "DH_MOHANG",
                            Price = 10000.0,
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            OrderId = "DH_MOHANG",
                            Price = 15000.0,
                            ProductId = 2,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("FirstWebMVC.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductName = "Sữa Vinamilk",
                            ProductPrice = 10000.0
                        },
                        new
                        {
                            Id = 2,
                            ProductName = "Bánh Mì Ngọt",
                            ProductPrice = 15000.0
                        });
                });

            modelBuilder.Entity("FirstWebMVC.Models.Entities.Student", b =>
                {
                    b.Property<string>("StudentCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaKhoa")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentCode");

                    b.HasIndex("MaKhoa");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("FirstWebMVC.Models.Entities.Order", b =>
                {
                    b.HasOne("FirstWebMVC.Models.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FirstWebMVC.Models.Entities.OrderDetail", b =>
                {
                    b.HasOne("FirstWebMVC.Models.Entities.Order", "Order")
                        .WithMany("OrderDetail")
                        .HasForeignKey("OrderId");

                    b.HasOne("FirstWebMVC.Models.Entities.Product", "Product")
                        .WithMany("OrderDetail")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FirstWebMVC.Models.Entities.Student", b =>
                {
                    b.HasOne("FirstWebMVC.Models.Entities.Faculty", "ThongTinKhoa")
                        .WithMany("DanhSachSinhVien")
                        .HasForeignKey("MaKhoa");

                    b.Navigation("ThongTinKhoa");
                });

            modelBuilder.Entity("FirstWebMVC.Models.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FirstWebMVC.Models.Entities.Faculty", b =>
                {
                    b.Navigation("DanhSachSinhVien");
                });

            modelBuilder.Entity("FirstWebMVC.Models.Entities.Order", b =>
                {
                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("FirstWebMVC.Models.Entities.Product", b =>
                {
                    b.Navigation("OrderDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
