// <auto-generated />
using FirstWebMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstWebMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260412130731_CapNhapBangKhoa")]
    partial class CapNhapBangKhoa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("FirstWebMVC.Models.Entities.Faculty", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoas");

                    b.HasData(
                        new
                        {
                            MaKhoa = "CNTT",
                            TenKhoa = "Công nghệ thông tin"
                        },
                        new
                        {
                            MaKhoa = "KETOAN",
                            TenKhoa = "Kế toán"
                        },
                        new
                        {
                            MaKhoa = "QTKD",
                            TenKhoa = "Quản trị kinh doanh"
                        },
                        new
                        {
                            MaKhoa = "CD",
                            TenKhoa = "Cơ điện"
                        });
                });

            modelBuilder.Entity("FirstWebMVC.Models.Entities.Student", b =>
                {
                    b.Property<string>("StudentCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaKhoa")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentCode");

                    b.HasIndex("MaKhoa");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("FirstWebMVC.Models.Entities.Student", b =>
                {
                    b.HasOne("FirstWebMVC.Models.Entities.Faculty", "ThongTinKhoa")
                        .WithMany("DanhSachSinhVien")
                        .HasForeignKey("MaKhoa");

                    b.Navigation("ThongTinKhoa");
                });

            modelBuilder.Entity("FirstWebMVC.Models.Entities.Faculty", b =>
                {
                    b.Navigation("DanhSachSinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
